version: '3.8'

services:
  weibo-signin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weibo-signin
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env:ro
    environment:
      - TZ=Asia/Shanghai
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 